### ISSUE TITLE
I have some problem with your codes . I haven't modified your code

### ISSUE THREAD

**Issue by UNITYli** [DespinaChristou/REDSandT#2]
Traceback (most recent call last):
  File "redsandt.py", line 68, in <module>
    framework.train_model()
  File "/content/REDSandT-main/redsandt/framework/bag_re.py", line 107, in train_model
    logits = self.model(label, scope, *args, bag_size=self.bag_size)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/REDSandT-main/redsandt/selector/bag_attention.py", line 89, in forward
    rep = self.sentence_encoder(token, mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/REDSandT-main/redsandt/encoder/bert_encoder.py", line 133, in forward
    head_hidden = (head_sent_positions.unsqueeze(2) * hidden).sum(1)
TypeError: only integer tensors of a single element can be converted to an index

**Comment by DespinaChristou** [comment]
I am suspecting you're using different libraries versions. Please use versions listed in requirements.txt

**Comment by UNITYli** [comment]
> I am suspecting you're using different libraries versions. Please use versions listed in requirements.txt

Thank you for your answer. I have solved the problem。
